# Generated by Django 4.2.6 on 2023-10-08 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('newsObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_first_app.news')),
            ],
        ),
    ]
