# Generated by Django 4.2.6 on 2023-10-11 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_app', '0003_gallery_alter_news_options_news_like_count_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comments',
        ),
    ]
